import './styles/globals.scss'
import {Montserrat} from 'next/font/google'
import {Header} from "@/app/components/header/Header";

const montserrat = Montserrat({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}) {
  return (
      <html lang="ru">
      <body className={montserrat.className}>
      <Header/>
      <main className='main'>
        <div className="container">
          {children}
        </div>
      </main>
      </body>
      </html>
  )
}
